### ISSUE TITLE
RISK:évaluation et méthodes d'évaluation

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/digiriskdolibarr#29]
Conclusions : 
On ne garde pas l'historique des la description du risque
1 Evaluation = 1 cotation + 1 date + 1 commentaire
Données du risque : 
1 risque, 1 description, N évaluations, N taches

**Comment by lmag** [comment]
Questions sur l'archivage des commentaires 3 options possibles : 
1) Description sur le risque, Description sur la cotation, taches(statuts)

Sur la version 2.0.0 sur DigiriskDolibarr
2) Description sur le risque, Cotation, Taches(statuts)

Sur DigiRisk version 7.6.5, On 3 : 
3) Pas de description sur le risque, Description sur la cotation, Taches si Task manager

**Comment by lmag** [comment]
On pourrait mettre en place : 
Description sur le risque, Description sur la cotation, taches(statuts) à étudier au niveau IHM
![image](https://user-images.githubusercontent.com/3288514/108395271-e8c47180-7215-11eb-9add-a2fbf20c326e.png)

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/108395707-5c667e80-7216-11eb-9b25-65aca441735e.png)

**Comment by lmag** [comment]
1 risque, 1 description 
1 évaluation, 1 date, 1 commentaire
N taches

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/109009854-5a396f80-76af-11eb-8af2-a25f3f306b96.png)

**Comment by lmag** [comment]
Evaluation = Cotation + date + commentaire

**Comment by eoxia-amandine** [comment]
Proposition pour l'ajout d'une évaluation :
![modals](https://user-images.githubusercontent.com/18576747/109136092-0afb4980-7758-11eb-9844-196c03f9c260.png)

**Comment by eoxia-amandine** [comment]
V9 listing mod dolibarr avec ajout de risque :

![listing-v9](https://user-images.githubusercontent.com/18576747/109931390-15be5d00-7cc9-11eb-9e20-4ef502282214.png)

**Comment by eoxia-amandine** [comment]
Vue complète de la V9 avec Dolibarr

![listing-v9-dolidigirisk](https://user-images.githubusercontent.com/18576747/110090100-30f79e00-7d97-11eb-831c-8c1103404694.png)

**Comment by eoxia-amandine** [comment]
Suite à la réunion :

![listing-v9-dolidigirisk-complet](https://user-images.githubusercontent.com/18576747/110097331-2f31d880-7d9f-11eb-8e55-424cc1eab32d.png)
