### ISSUE TITLE
Photo des risques

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/digiriskdolibarr#38]
o   -       créer un dossier média dans le dossier digiriskdolibarr dans ecm files

-       dans la popup, afficher la vue de la GED du dossier média
-       envoyer le fichier dans un dossier ecm files dans digiriskdolibarr, à la création du risque déplacer le fichier dans le dossier risque avec la bonne réf ou stocker dans l’objet risque (ou évaluation) l’id d’ecm dans has_photo (qu’il faut d’ailleurs renommer)

- [x] action create
- [x] action view
- [x] action edit

**Comment by nicolas-eoxia** [comment]
OK fait
